destapais/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
import users

urlpatterns = [
    path('', include('users.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = users.views.handler404

users/urls.py
from django.urls import path, re_path, include

from . import views

from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('degustaciones/', include([
        path('', views.DegustacionesView.as_view(), name='degustaciones-list'),
        path('create/', login_required(views.DegustacionCreateView.as_view()),
             name='degustacion-create'),
        path('<int:pk>/details/',
             views.DegustacionDetailsView.as_view(), name='degustacion-details'),
        path('<int:pk>/calificar/<int:voto>/',
             login_required(views.calificar_degustacion), name='calificar-degustacion'),
        path('<int:pk>/comentario/', login_required(views.ComentarioCreateView.as_view()),
             name='degustacion-crear-comentario'),
    ])),
    path('perfil/', include([
        path('', login_required(views.PerfilView.as_view()), name='perfil-details'),
        path('editar/', login_required(views.UpdatePerfilView.as_view()),
             name='perfil-update'),
        path('degustaciones/', include([
            path('', login_required(views.PerfilDegustacionesView.as_view()),
                 name='perfil-degustaciones'),
            path('<int:pk>/editar/', login_required(views.DegustacionUpdateView.as_view()),
                 name='degustacion-update'),
            path('<int:pk>/borrar/', login_required(views.DegustacionDeleteView.as_view()),
                 name='degustacion-delete')
        ])),
        path('calificaciones/',
             login_required(views.PerfilCalificacionesView.as_view()),
             name='perfil-calificaciones'),
        path('amigos/', include([
            path('', login_required(views.AmigosView.as_view()),
                 name='perfil-amigos'),
            path('<int:pk>/borrar', login_required(views.borrar_amigo),
                 name='borrar-amigo'),
            path('<int:pk>/bloquear', login_required(views.bloquear_amigo),
                 name='bloquear-amigo'),
            path('<int:pk>/desbloquear', login_required(views.desbloquear_amigo),
                 name='desbloquear-amigo')
        ])),
        path('locales/', include([
            path('favoritos/', login_required(views.PerfilLocalesFavoritosView.as_view()),
                 name='perfil-locales'),
            path('<int:pk>/editar/',
                 login_required(views.LocalUpdateView.as_view()), name='local-update'),
            path('<int:pk>/borrar/',
                 login_required(views.LocalDeleteView.as_view()), name='local-delete')
        ])),
        path('galardones', include([
            path('', login_required(views.PerfilGalardonesView.as_view()),
                 name='perfil-galardones'),
        ])),
        path('actividades', include([
            path('', login_required(views.PerfilActividadView.as_view()),
                 name='perfil-actividades'),
            path('<int:pk>/vista', login_required(views.actividad_vista),
                 name='visitar-actividad')
        ])),
        path('peticiones/', include([
            path('recibidas/', login_required(views.PeticionesRecibidasView.as_view()),
                 name='peticiones-recibidas'),
            path('<int:pk>/aceptar', login_required(views.aceptar_peticion_amistad),
                 name='aceptar-peticion'),
            path('<int:pk>/denegar', login_required(views.denegar_peticion_amistad),
                 name='denegar-peticion'),
        ]))
    ])),
    path('locales/', include([
        path('', views.LocalesView.as_view(), name='locales-list'),
        path('<int:pk>/details/', views.LocalView.as_view(), name='local-details'),
        path('<int:pk>/crear-degustacion/', login_required(views.LocalCrearDegustacionView.as_view()),
             name='local-crear-degustacion'),
        path('create/', login_required(views.LocalCreateView.as_view()),
             name='local-create'),
        path('<int:pk>/add-me-gusta/',
             login_required(views.add_local_me_gusta), name='add-me-gusta-local'),
        path('<int:pk>/delete-me-gusta/',
             login_required(views.delete_local_me_gusta), name='delete-me-gusta-local')
    ])),
    path('usuarios/', include([
        path('', views.UsuariosView.as_view(), name='usuarios-list'),
        path('<int:pk>/', include([
            path('details/', views.UsuarioDetailsView.as_view(),
                 name='usuario-details'),
            path('solicitud/', views.enviar_solicitud_amistad,
                 name='enviar-solicitud'),
            path('degustaciones/', views.UsuarioDegustacionesView.as_view(),
                 name='usuario-degustaciones'),
            path('calificaciones/', views.UsuarioCalificacionesView.as_view(),
                 name='usuario-calificaciones'),
            path('actividades/', views.UsuarioActividadView.as_view(),
                 name='usuario-actividades'),
        ]))
    ])),
    path('error/', views.InformeDeErrorView.as_view(),
         name='informe-error'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Avg, Count
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Q

from django_countries.fields import CountryField
# Create your models here.

ESTADO_PENDIENTE = 1
ESTADO_ACEPTADA = 2
ESTADO_DENEGADA = 3
ESTADO_BLOQUEADA = 4
ESTADO_AMISTAD = [
    (ESTADO_PENDIENTE, 'Pendiente'),
    (ESTADO_ACEPTADA, 'Aceptada'),
    (ESTADO_DENEGADA, 'Denegada'),
    (ESTADO_BLOQUEADA, 'Bloqueada'),
]


class Perfil(models.Model):
    '''Perfil del Usuario'''
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='perfil'
    )
    nombre = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200, null=True, blank=True)
    edad = models.PositiveIntegerField(
        validators=[MinValueValidator(18)], null=True)
    imagen = models.ImageField(
        upload_to='images/img_usuario/', default='images/img_usuario/None/no-img.jpg')
    descripcion = models.TextField(null=True, blank=True)
    pais = CountryField(null=True, blank=True)
    amigos = models.ManyToManyField(
        'self', symmetrical=False, through='Amigo', related_name='amigos+')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'{0}'.format(self.user_id)

    @property
    def nombre_completo(self):
        return '{} {}'.format(self.nombre, self.apellidos)

    @property
    def media_degustaciones(self):
        return self.creador.aggregate(
            media=Avg('calificaciones_degustacion__voto'))['media']

    @property
    def num_degustaciones(self):
        return self.creador.count()

    @property
    def num_calificaciones(self):
        return self.calificaciones_perfil.count()

    @property
    def tiene_actividades(self):
        return self.actividades.filter(vista=False).count() > 0

    def get_absolute_url(self):
        return reverse('usuario-details', args=[str(self.user_id)])

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def aniadir_amigo(self, perfil, estado=ESTADO_PENDIENTE):
        self.amigos.add(perfil)

    def borrar_amigo(self, perfil, symm=True):
        Amigo.objects.filter(
            de_perfil=self,
            a_perfil=perfil).delete()
        if symm:
            perfil.borrar_amigo(self, False)

    def aceptar_peticion(self, perfil):
        Amigo.objects.filter(
            de_perfil=perfil,
            a_perfil=self).update(estado=ESTADO_ACEPTADA)
        Amigo.objects.create(
            de_perfil=self,
            a_perfil=perfil,
            estado=ESTADO_ACEPTADA)

        self.actividades.create(accion='Has aceptado la peticion de amistad de {}.'.format(
            perfil.nombre), url=perfil.get_absolute_url())

        perfil.actividades.create(accion='{} ha aceptado tu peticion de amistad.'.format(
            self.nombre), url=self.get_absolute_url())

        galardon = Galardon.objects.get(slug='influencer')
        galardon_self = self.galardones_conseguidos.filter(galardon=galardon)
        if self.amigos.count() >= 80 and galardon_self.nivel == 4:
            galardon_self.update(nivel=5)
        elif self.amigos.count() >= 40 and galardon_self.nivel == 3:
            galardon_self.update(nivel=4)
        elif self.amigos.count() >= 20 and galardon_self.nivel == 2:
            galardon_self.update(nivel=3)
        elif self.amigos.count() >= 10 and galardon_self.nivel == 1:
            galardon_self.update(nivel=2)
        elif self.amigos.count() >= 5 and not galardon_self:
            self.galardones_conseguidos.create(galardon=galardon, nivel=1)

        galardon_perfil = perfil.galardones_conseguidos.filter(
            galardon=galardon)
        if perfil.amigos.count() >= 80 and galardon_perfil.nivel == 4:
            galardon_perfil.update(nivel=5)
        elif perfil.amigos.count() >= 40 and galardon_perfil.nivel == 3:
            galardon_perfil.update(nivel=4)
        elif perfil.amigos.count() >= 20 and galardon_perfil.nivel == 2:
            galardon_perfil.update(nivel=3)
        elif perfil.amigos.count() >= 10 and galardon_perfil.nivel == 1:
            galardon_perfil.update(nivel=2)
        elif perfil.amigos.count() >= 5 and not galardon_perfil:
            perfil.galardones_conseguidos.create(galardon=galardon, nivel=1)

    def denegar_peticion(self, perfil):
        Amigo.objects.filter(
            a_perfil=self,
            de_perfil=perfil).update(estado=ESTADO_DENEGADA)

    def bloquear_amigo(self, perfil):
        Amigo.objects.filter(
            de_perfil=self,
            a_perfil=perfil).update(estado=ESTADO_BLOQUEADA)

    def desbloquear_amigo(self, perfil):
        Amigo.objects.filter(
            de_perfil=self,
            a_perfil=perfil,
            estado=ESTADO_BLOQUEADA).update(estado=ESTADO_ACEPTADA)

    def lista_de_amigos(self, estado=None):
        bloqueado = Amigo.objects.filter(
            a_perfil=self, estado=ESTADO_BLOQUEADA).values('de_perfil')

        if estado:
            amigos = Amigo.objects.filter(
                de_perfil=self,
                estado=estado).exclude(a_perfil__in=bloqueado).values_list('a_perfil', flat=True)
            return Perfil.objects.filter(pk__in=amigos)
        else:
            amigos = Amigo.objects.filter(de_perfil=self).exclude(
                a_perfil__in=bloqueado).values_list('a_perfil', flat=True)
            return Perfil.objects.filter(pk__in=amigos)

    @property
    def peticiones_aceptadas(self):
        return self.lista_de_amigos(ESTADO_ACEPTADA)

    @property
    def peticiones_denegadas(self):
        return self.lista_de_amigos(ESTADO_DENEGADA)

    @property
    def peticiones_pendientes(self):
        return self.lista_de_amigos(ESTADO_PENDIENTE)

    @property
    def peticiones_bloqueadas(self):
        return self.lista_de_amigos(ESTADO_BLOQUEADA)

    def lista_peticiones_recividas(self):
        amigos = Amigo.objects.filter(
            a_perfil=self,
            estado=ESTADO_PENDIENTE).values_list('de_perfil', flat=True)

        return Perfil.objects.filter(pk__in=amigos)

    @property
    def peticiones_recibidas(self):
        return self.lista_peticiones_recividas()

    def calificar_degustacion(self, degustacion, voto):
        self.calificaciones_perfil.create(degustacion=degustacion, voto=voto)

    def add_me_gusta_local(self, local):
        self.me_gustas.add(local)

    def delete_me_gusta_local(self, local):
        self.me_gustas.remove(local)


@receiver(post_save, sender=User)
def update_user_perfil(sender, instance, created, **kwargs):
    if created:
        Perfil.objects.create(user=instance)
    instance.perfil.save()


class Amigo(models.Model):
    de_perfil = models.ForeignKey(
        Perfil, on_delete=models.CASCADE, related_name='enviadas')
    a_perfil = models.ForeignKey(
        Perfil, on_delete=models.CASCADE, related_name='recibidas')
    estado = models.IntegerField(
        choices=ESTADO_AMISTAD, default=ESTADO_PENDIENTE)
    # Timestamp
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Amigo'
        verbose_name_plural = 'Amigos'
        unique_together = ['de_perfil', 'a_perfil']


class Local(models.Model):
    creador = models.ForeignKey(
        Perfil, on_delete=models.CASCADE, related_name='creador_local')
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=200, null=True, blank=True)
    resenia = models.TextField(null=True, blank=True)
    pais = CountryField()
    imagen = models.ImageField(
        upload_to='images/img_local/', default='images/img_local/None/no-img.jpg')
    me_gustas = models.ManyToManyField(
        Perfil, through='MeGusta', related_name='me_gustas')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'{0}'.format(self.nombre)

    def get_absolute_url(self):
        return reverse('local-details', args=[str(self.id)])

    class Meta:
        verbose_name = 'Local'
        verbose_name_plural = 'Locales'


class MeGusta(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    local = models.ForeignKey(Local, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Me Gusta'
        verbose_name_plural = 'Me Gustas'
        unique_together = ['perfil', 'local']


TIPO_BEBIDA = 0
TIPO_COMIDA = 1
TIPO_TAPA = 2
TIPO_COCTEL = 3
TIPO_RACION = 4
TIPOS = [
    (TIPO_BEBIDA, 'Bebida'),
    (TIPO_COMIDA, 'Comida'),
    (TIPO_TAPA, 'Tapa'),
    (TIPO_COCTEL, 'Coctel'),
    (TIPO_RACION, 'Racion'),
]

TAMANIO_PEQUENIA = 0
TAMANIO_MEDIANA = 1
TAMANIO_GRANDE = 2
TAMANIOS = [
    (TAMANIO_PEQUENIA, 'Pequeña'),
    (TAMANIO_MEDIANA, 'Mediana'),
    (TAMANIO_GRANDE, 'Grande'),
]

GUSTO_DULCE = 0
GUSTO_SALADO = 1
GUSTO_ACIDO = 2
GUSTO_PICANTE = 3
GUSTO_AMARGO = 4
GUSTO_AFRUTADO = 5
GUSTO_UMAMI = 6
GUSTOS = [
    (GUSTO_DULCE, 'Dulce'),
    (GUSTO_SALADO, 'Salado'),
    (GUSTO_ACIDO, 'Acido'),
    (GUSTO_PICANTE, 'Picante'),
    (GUSTO_AMARGO, 'Amargo'),
    (GUSTO_AFRUTADO, 'Afrutado'),
    (GUSTO_UMAMI, 'Umami'),
]


class Degustacion(models.Model):
    creador = models.ForeignKey(
        Perfil, on_delete=models.CASCADE, related_name='creador')
    local = models.ForeignKey(
        Local, on_delete=models.CASCADE, related_name='degustacion_local')
    nombre = models.CharField(max_length=50)
    imagen = models.ImageField(
        upload_to='images/img_degustacion/', default='images/img_degustacion/None/no-img.jpg')
    descripcion = models.TextField()

users/forms.py
from django import forms

from django.utils.translation import gettext_lazy

from .models import *


class AmigosForm(forms.ModelForm):

    class Meta:
        model = Amigo
        exclude = []

    def clean(self):
        super(AmigosForm, self).clean()  # Thanks, @chefsmart
        de_perfil = self.cleaned_data.get('de_perfil', None)
        a_perfil = self.cleaned_data.get('a_perfil', None)
        if de_perfil == a_perfil:
            message = 'No pueden ser la misma id'
            raise forms.ValidationError(message)
        return self.cleaned_data


class PerfilForm(forms.ModelForm):
    imagen = forms.ImageField(required=True)

    class Meta:
        model = Perfil
        exclude = []


class DegustacionForm(forms.ModelForm):
    imagen = forms.ImageField(required=True)

    def clean(self):
        cleaned_data = super().clean()
        imagen = cleaned_data.get('imagen')
        if not imagen:
            data = 'images/img_degustacion/None/no-img.jpg'

    class Meta:
        model = Degustacion
        exclude = ['creador', 'calificaciones']


class LocalForm(forms.ModelForm):
    imagen = forms.ImageField(required=True)

    def clean(self):
        cleaned_data = super().clean()
        imagen = cleaned_data.get('imagen')
        if not imagen:
            data = 'images/img_local/None/no-img.jpg'

    class Meta:
        model = Local
        fields = ['nombre', 'pais', 'direccion', 'resenia', 'imagen']
        labels = {
            'resenia': gettext_lazy('Reseña'),
        }

users/templates/homepage.html
{% extends 'index.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section ftco-animate text-center">
                <a href="{% url 'degustaciones-list' %}"><h2 class="mb-4">Degustaciones</h2></a>
                <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
            </div>
        </div>
        <div class="row">
            {% for degustacion in degustaciones %}
            <div class="col-md-6 col-lg-3 text-center ftco-animate">
                <div class="menu-wrap">
                    <a href="{{ degustacion.get_absolute_url }}" class="menu-img img mb-4" style="background-image: url(/media/{{ degustacion.imagen }});"></a>
                    <div class="text">
                        <h3><a href="{{ degustacion.get_absolute_url }}">{{ degustacion.nombre }}</a></h3>
                        <p class="price">
                            <span>
                                {% for _ in ''|center:5 %}
                                    {% if forloop.counter <= degustacion.calificacion_media %}
                                        <i class="fas fa-star"></i>
                                    {% else %}
                                        <i class="far fa-star"></i>
                                    {% endif %}
                                {% endfor %}
                                <span style="color: rgba(255,255,255,0.5)">({{ degustacion.num_calificaciones }})</span>
                            </span>
                        </p>
                        <p>{{ degustacion.descripcion|default_if_none:'Sin descripcion'|truncatewords:10 }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                No hay degustaciones
            </div>
            {% endfor %}
        </div>

    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section ftco-animate text-center">
                <a href="{% url 'locales-list' %}"><h2 class="mb-4">Locales</h2></a>
                <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
            </div>
        </div>
        <div class="row">
             {% for local in locales %}
            <div class="col-md-6 col-lg-3 text-center ftco-animate">
                <div class="menu-wrap">
                    <a href="{{ local.get_absolute_url }}" class="menu-img img mb-4" style="background-image: url(/media/{{ local.imagen }});"></a>
                    <div class="text">
                        <h3>
                            {% if user.is_authenticated %}
                                {% if user.perfil in local.me_gustas.all %}
                                    <a href="{% url 'delete-me-gusta-local' pk=local.pk %}"><i class="fas fa-heart" style="color: red;"></i></a>
                                {% else %}
                                    <a href="{% url 'add-me-gusta-local' pk=local.pk %}"><i class="far fa-heart"></i></a> 
                                {% endif %}
                            {% endif %}
                            <a href="{{ local.get_absolute_url }}">{{ local.nombre }}</a>
                        </h3>
                        <p><a href="#"><i class="{{ local.pais.flag_css }}"></i> {{ local.pais.name }}</a></p>
                        <p>{{ local.resenia|default_if_none:'Sin descripcion'|truncatewords:10 }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                No hay locales
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section ftco-animate text-center">
                <a href="{% url 'usuarios-list' %}"><h2 class="mb-4">Usuarios</h2></a>
                <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
            </div>
        </div>
        <div class="row">
             {% for usuario in usuarios %}
            <div class="col-md-6 col-lg-3 text-center ftco-animate">
                <div class="menu-wrap">
                    <a href="{% url 'usuario-details' pk=usuario.pk %}" class="menu-img img mb-4" style="background-image: url(/media/{{ usuario.imagen }});"></a>
                    <div class="text">
                        <h3><a href="{% url 'usuario-details' pk=usuario.pk %}">{{ usuario.nombre }}</a></h3>
                        <p class="price">
                            <span>
                                <i class="fas fa-star"></i> {{ usuario.media_degustaciones|default_if_none:'0.0'|floatformat:'1' }} 
                                <span style="color: rgba(255,255,255,0.5)">({{ usuario.num_degustaciones }})</span>
                            </span>
                        </p>
                        <p>
                            {% if user.is_authenticated %}
                                {% if usuario in user.perfil.peticiones_aceptadas %}
                                    <a href="{% url 'usuario-details' usuario.pk %}" class="btn btn-sm btn-outline-secondary" tabindex="-1" role="button" aria-disabled="true">Amigo</a>
                                {% elif usuario in user.perfil.peticiones_pendientes %}
                                    <a href="{% url 'usuario-details' usuario.pk %}" class="btn btn-sm btn-outline-secondary" tabindex="-1" role="button" aria-disabled="true">Pendiente</a>
                                {% elif usuario == user.perfil %}
                                    <a href="{% url 'perfil-details' %}" class="btn btn-sm btn-outline-success" tabindex="-1" role="button" aria-disabled="true">Eres tu</a>
                                {% else %}
                                    <a href="{% url 'enviar-solicitud' usuario.pk %}" class="btn btn-sm btn-primary">Enviar solicitud</a>
                                {% endif %}
                            {% endif %}
                        </p>
                        <p>{{ usuario.descripcion|default_if_none:'Sin descripcion'|truncatewords:10 }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                No hay usuarios
            </div>
            {% endfor %}
        </div>
    </div>
</section>
    
{% endblock %}

users/templates/informe-error.html
{% extends 'index.html' %}

{% block title %}Informe de error{% endblock %}

{% load bootstrap4 %}

{% block content %}
<section  class="ftco-section">
        <div class="container">
            <div class="row justify-content-center mb-2 pb-2">
                <div class="col-md-7 heading-section ftco-animate text-center">
                    <h2 class="mb-4">Informar de un error</h2>
                </div>
            </div>
            <div class="row justify-content-center mb-2 pb-2">
                <form method="post" class="form" enctype="multipart/form-data">

                    <div class="form-group"><input type="email" name="email" placeholder="Email" maxlength="200" class="form-control" title="Required" required id="id_email">
                        <small class="form-text text-muted">Required</small>

                    </div>

                    <div class="form-group"><label for="id_imagen">Imagen del error</label><input type="file" name="imagen" accept="image/*" class="form-control-file" title="" required id="id_imagen"></div>

                    <div class="form-group"><label for="id_descripcion">Descripcion del error</label><input type="text" name="descripcion" class="form-control" placeholder="Descripcion" title="" required id="id_descripcion"></div>

                    <div class="form-group">
                        <input type="submit" value="Enviar informe" class="btn btn-primary py-3 px-4">
                        <a class="btn btn-danger py-3 px-4">Cancelar</a>
                    </div> 
                </form>
            </div>
        </div>
    </section>

{% endblock %}